/* Write MAP.md: every top-level symbol and class method, with its line.
 *
 *   node scripts/index-symbols.mjs        -> MAP.md
 *   node scripts/index-symbols.mjs --check  (non-zero if MAP.md is stale)
 *
 * The point is to stop reading whole files. `world.js` is thirteen hundred
 * lines; finding one method in it by reading it costs about as much as the
 * rest of a session's edits put together. With a line number the read is
 * twenty lines instead.
 *
 * Deliberately regex, not a parser: a dependency would be the first one in
 * this repo, and the declaration forms here are uniform enough that the naive
 * match is right. The forms it knows about are asserted by --check, which
 * fails if the file drifts.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const OUT = join(ROOT, 'MAP.md');

const files = execFileSync('git', ['ls-files', '*.js', '*.mjs'], { cwd: ROOT })
  .toString().trim().split('\n')
  .filter((f) => !f.startsWith('scripts/'))
  .sort();

/* A top-level function, class, or exported binding. */
const TOP = /^(?:export\s+)?(?:async\s+)?(function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/;
/* A method inside a class body: two-space indent, name, parens, brace. */
const METHOD = /^  (?:static\s+|get\s+|set\s+|async\s+)*([A-Za-z_$][\w$]*)\s*\(/;
/* Section banners the source already uses to group related code. */
const BANNER = /^\s*(?:\/\/|\/\*+)\s*-{2,}\s*(.+?)\s*-{2,}/;

const RESERVED = new Set(['if', 'for', 'while', 'switch', 'catch', 'return', 'constructor']);

const out = [
  '# MAP',
  '',
  '_Generated by `node scripts/index-symbols.mjs`. Do not edit._',
  '',
  'Every top-level symbol and class method, with the line it starts on, so a',
  'lookup is `sed -n \'START,+30p\' file` rather than reading the whole thing.',
  'Regenerate after moving code; `--check` fails if it is stale.',
  '',
];

let total = 0;
for (const f of files) {
  const src = await readFile(join(ROOT, f), 'utf8');
  const lines = src.split('\n');
  const entries = [];
  let cls = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const top = TOP.exec(line);
    if (top && !RESERVED.has(top[2])) {
      cls = top[1] === 'class' ? top[2] : null;
      const kind = top[1] === 'class' ? 'class'
        : top[1] === 'function' ? 'fn' : 'const';
      entries.push(`${i + 1} ${kind} ${top[2]}`);
      continue;
    }
    if (cls) {
      const m = METHOD.exec(line);
      if (m && !RESERVED.has(m[1]) && !line.trimStart().startsWith('*')) {
        entries.push(`${i + 1} · ${cls}.${m[1]}`);
        continue;
      }
    }
    const b = BANNER.exec(line);
    if (b && b[1].length < 60) entries.push(`${i + 1} — ${b[1]}`);
  }

  total += entries.length;
  out.push(`## ${f}  (${lines.length} lines)`, '', '```');
  out.push(...entries);
  out.push('```', '');
}

const body = out.join('\n');

if (process.argv.includes('--check')) {
  const current = await readFile(OUT, 'utf8').catch(() => '');
  if (current !== body) {
    console.error('MAP.md is stale — run: node scripts/index-symbols.mjs');
    process.exit(1);
  }
  console.log(`MAP.md is current (${total} symbols across ${files.length} files)`);
} else {
  await writeFile(OUT, body, 'utf8');
  console.log(`${relative(ROOT, OUT)} — ${total} symbols across ${files.length} files`);
}
